### ISSUE TITLE
Metoda vyhralPosledniTah

### ISSUE THREAD

**Issue by atiti11** [tomas2211/piskvorky#1]
Metoda vyhralPoslednitah() vrací True a None místo True a False - je to matoucí pro další použití

**Comment by pograjak** [comment]
@atiti11 Doufam ze jsi Anicka. 👋  Skvely, ze sis vsimla. Udelas PR? Btw pry jsi mela nejake otazky k Node.js, tak mi klidne napis. :]

**Comment by atiti11** [comment]
Jojo, jsem Anička. Všimla jsem si, protože mi to na tom padalo...Co znamená PR? Jinak s Node.js jsem teď chvíli zase v pohodě, ale určitě se zase něco pokazí, takže určitě napíšu. :)

**Comment by pograjak** [comment]
@atiti11 Jo promin. PR je zkratka pro Pull Request, je to metoda, jak přidávat změny do repozitáře ve více lidech, který se používá skoro ve všech firmách. Upravil jsem to [tady v PR](https://github.com/tomas2211/piskvorky/pull/2) a @tomas2211 teď může zkontrolovat jestli se mu mnou navržená změna líbí a případně ji akceptuje. :)

**Comment by atiti11** [comment]
Ok, díky. Dokonce asi vím, jak bych to udělala.:)

**Comment by tomas2211** [comment]
Good catch, fixed in https://github.com/tomas2211/piskvorky/pull/2
